name = "drive2earn"
compatibility_date = "2024-03-19"

# We're only tracking website files in Git, not the worker itself
# The worker is managed directly on Cloudflare

# Use Cloudflare Pages deployment settings
[build]
command = ""  # No build command needed for static files

[site]
bucket = "."    # The directory containing your static files

[deploy]
mode = "directory"  # Deploy as a directory of static files
