name = "drive2earn"
main = "worker.js"
compatibility_date = "2024-03-19"

routes = [
  { pattern = "drive2earn.digitalnomads.workers.dev/token-prices*", zone_name = "digitalnomads.workers.dev" }
]

[build]
command = ""
[build.upload]
format = "service-worker"
