name = "drive2earn"
compatibility_date = "2024-03-19"

# We're only tracking website files in Git, not the worker itself
# The worker is managed directly on Cloudflare

[site]
bucket = "./"

[build]
command = "echo 'Deploying website files only'"
